apiVersion: v1
kind: Service
metadata:
  name: inventory-consumer-service
spec:
  selector:
    app: inventory-consumer-service
  ports:
    - port: 9092
      targetPort: 9090
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-consumer-service
  labels:
    app: inventory-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-consumer-service
  template:
    metadata:
      labels:
        app: inventory-consumer-service
    spec:
      containers:
      - name: inventory-consumer-service
        image: swr.cn-north-4.myhuaweicloud.com/itau-demo/inventory-service:0.0.1
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "2Gi"
            cpu: "2000m"
          requests:
            memory: "1Gi"
            cpu: "1000m"
        env:
          - name: AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT
            value: "true"
          - name: DB_HOST_AND_PORT
            value: "http://172.16.0.248:80"
          - name: DB_USERNAME
            value: "rwuser"
          - name: DB_PASSWORD
            value: "Huawei@#123"
          - name: DMS_HOST_AND_PORT
            value: "172.16.0.46:9092,172.16.0.191:9092,172.16.0.138:9092"
          - name: DMS_TOPIC
            value: "topic-inventory"
          - name: DMS_PARTITION
            value: "0"
          - name: DMS_CONSUMER
            value: "true"
          - name: DMS_CONSUMER_GROUP_ID
            value: "test-group"
          - name: DMS_CONSUMER_ENABLE_AUTO_COMMIT
            value: "false"
          - name: DMS_CONSUMER_AUTO_COMMIT_INTERVAL_MS
            value: "1000"
          - name: DMS_CONSUMER_POLL_DURATION
            value: "1000"
          - name: DMS_CONSUMER_MAX_POLL_RECORDS
            value: "500"
          - name: DMS_CONSUMER_MAX_POLL_INTERVAL_MS
            value: "500"
          - name: DMS_CONSUMER_CONNECTIONS_MAX_IDLE_MS
            value: "600000"
          - name: DMS_CONSUMER_HEARTBEAT_INTERVAL_MS
            value: "300"
          - name: DMS_CONSUMER_SESSION_TIMEOUT_MS
            value: "10000"
          - name: DMS_CONSUMER_FETCH_MAX_BYTES
            value: "1000000"
          - name: DMS_CONSUMER_AUTO_OFFSET_RESET
            value: "latest"
        imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
      - name: default-secret

